import _Navbar from "@/components/Layouts/Navbar";
import type { Metadata } from "next";

// import "@nextui-org/theme/dist/nextui.css";  

export const metadata: Metadata = {
  title: "Create BY Reno A",
  description: "Generated by create next app",
};

export default function WebLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <_Navbar />
      <main className="w-full">{children}</main>;
    </>
  );
}
