import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create BY Reno A",
  description: "Generated by create next app",
};

export default function WebLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <main className="w-full">{children}</main>
    </>
  );
}
